---
name: 'Python Setup'
description: 'Sets up a Python runtime with uv'
inputs:
  uv-version:
    description: 'Which version of uv to use.'
    required: false
    default: "latest"
  cache-prefix:
    description: 'Prefix to attach to the virtual-envrionment cache.'
    required: false
    default: "uv-venv"
runs:
  using: 'composite'
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        version: ${{ inputs.uv-version }}
        cache-suffix: ${{ inputs.cache-prefix}}
